# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: "Code freeze"

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Type of release
        options: 
        - major
        - minor
      freeze-commit:
        type: string
        description: Commit SHA to use for cut-off
        required: false
        default: main
      dry-run:
        type: boolean
        description: Dry-run of code-freeze
        required: false
        default: true
jobs:
  code-freeze:
    # TODO(kajalj): repin to a released tag once NVIDIA-NeMo/FW-CI-templates#586 merges.
    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_code_freeze.yml@50bd10c4e8b512ed5184cfe89fd9a8dc4d8ecc11
    with:
      library-name: NeMo-RL
      python-package: nemo_rl
      release-type: ${{ inputs.release-type }}
      freeze-commit: ${{ inputs.freeze-commit }}
      dry-run: ${{ inputs.dry-run }}
      next-pre-release: ""
      next-dev: ""
      use-pat: true
      cherry-pick-psa: >-
        PSA: For automated cherry picks back to `main`, assign the label `cherry-pick-to-main` to your PR
        _before_ merging to `{RELEASE_BRANCH}`. A bot will attempt a cherry pick into `main`. If it fails
        due to a merge-conflict, you'll get pinged in #swdl-nemo-rl-alerts and will need to take action —
        no one will proactively reach out.
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_RELEASE_ENDPOINT }}
      SLACK_WEBHOOK_ADMIN: ${{ secrets.SLACK_WEBHOOK_ADMIN }}
      PAT: ${{ secrets.PAT }}
